apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pardini01-nginx
  name: pardini01-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pardini01-nginx
  template:
    metadata:
      labels:
        app: pardini01-nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 80

