apiVersion: v1
kind: Service
metadata:
  labels:
    app: pardini01-nginx
  name: pardini01-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pardini01-nginx
  type: NodePort

